name: Latest blog post workflow
on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
  name: "update this repo's README with Latest"
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: gautamkrishnar/blog-post-workflow@master
    with:
      feed_list: "https://dev.to/feed/codestackr"
  